"""add project contributors

Revision ID: cb8f161b6e0d
Revises: 9c941bc3f71f
Create Date: 2025-12-03 15:05:39.926307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb8f161b6e0d'
down_revision = '9c941bc3f71f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_contributors',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.add_column('anexos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('checkins', 'hora_chegada',
               existing_type=mysql.TIME(),
               nullable=True)
    op.drop_index('idx_projetos_active_status_id', table_name='projetos')
    op.drop_index('idx_projetos_client_status', table_name='projetos')
    op.drop_index('idx_projetos_overdue', table_name='projetos')
    op.drop_index('idx_projetos_responsavel_active', table_name='projetos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_projetos_responsavel_active', 'projetos', ['responsavel_id', 'deleted_at', 'status'], unique=False)
    op.create_index('idx_projetos_overdue', 'projetos', ['status', 'data_fim_prevista', 'deleted_at'], unique=False)
    op.create_index('idx_projetos_client_status', 'projetos', ['cliente_id', 'status', 'deleted_at'], unique=False)
    op.create_index('idx_projetos_active_status_id', 'projetos', ['deleted_at', 'status', 'id'], unique=False)
    op.alter_column('checkins', 'hora_chegada',
               existing_type=mysql.TIME(),
               nullable=False)
    op.drop_column('anexos', 'deleted_at')
    op.drop_table('project_contributors')
    # ### end Alembic commands ###