"""fix_schema_mismatch

Revision ID: 9c941bc3f71f
Revises: add_performance_indexes
Create Date: 2025-11-28 18:21:20.600220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c941bc3f71f'
down_revision = 'add_performance_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop dependent tables first (to avoid FK errors when dropping checkins)
    try:
        op.drop_table('tarefas_executadas') # Obsolete table
    except Exception:
        pass
        
    try:
        op.drop_table('anexos') # Dependent on checkins, will recreate
    except Exception:
        pass

    # 2. Drop foreign keys on checkins (if any exist)
    try:
        op.drop_constraint('checkins_ibfk_2', 'checkins', type_='foreignkey')
        op.drop_constraint('checkins_ibfk_1', 'checkins', type_='foreignkey')
    except Exception:
        pass

    # 3. Drop obsolete tables
    try:
        op.drop_table('projects')
    except Exception:
        pass
        
    try:
        op.drop_index('email', table_name='users')
        op.drop_table('users')
    except Exception:
        pass

    # 4. Drop and Recreate checkins table
    try:
        op.drop_table('checkins')
    except Exception:
        pass
    
    op.create_table('checkins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.Column('projeto_id', sa.Integer(), nullable=False),
        sa.Column('data_inicio', sa.Date(), nullable=False),
        sa.Column('hora_inicio', sa.Time(), nullable=False),
        sa.Column('data_fim', sa.Date(), nullable=True),
        sa.Column('hora_fim', sa.Time(), nullable=True),
        sa.Column('duracao_minutos', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO', name='checkinstatus'), nullable=False),
        sa.Column('localizacao_inicio', sa.String(length=500), nullable=True),
        sa.Column('localizacao_fim', sa.String(length=500), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for checkins
    op.create_index(op.f('ix_checkins_data_fim'), 'checkins', ['data_fim'], unique=False)
    op.create_index(op.f('ix_checkins_data_inicio'), 'checkins', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_projeto_id'), 'checkins', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_checkins_status'), 'checkins', ['status'], unique=False)
    op.create_index(op.f('ix_checkins_usuario_id'), 'checkins', ['usuario_id'], unique=False)
    
    # 5. Recreate anexos table
    op.create_table('anexos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('checkin_id', sa.Integer(), nullable=False),
        sa.Column('nome_original', sa.String(length=255), nullable=False),
        sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
        sa.Column('tipo_arquivo', sa.String(length=100), nullable=False),
        sa.Column('tamanho', sa.Integer(), nullable=False),
        sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome_arquivo')
    )
    op.create_index(op.f('ix_anexos_checkin_id'), 'anexos', ['checkin_id'], unique=False)
    op.create_index(op.f('ix_anexos_id'), 'anexos', ['id'], unique=False)

    # Drop indexes that shouldn't be there (commented out to avoid errors)
    # op.drop_index('idx_projetos_active_status_id', table_name='projetos')
    # op.drop_index('idx_projetos_client_status', table_name='projetos')
    # op.drop_index('idx_projetos_overdue', table_name='projetos')
    # op.drop_index('idx_projetos_responsavel_active', table_name='projetos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
